### PR TITLE
Node 10

### PR DESCRIPTION
**Pull request by daviddias**

### CODE REVIEW

**Comment by victorb** [comment]
Hm, let's add node 10 to the jenkinsfile and leave the others alone as-is.

**Comment by daviddias** [comment]
Why update one CI and not all?

**Comment by victorb** [comment]
@diasdavid plan is and has been for a while now to not continue using CircleCI, TravisCI or AppVeyor, so updating them is unnecessary

**Comment by daviddias** [comment]
This actually might be a cool change to do that CI Sync aka open PRS everywhere to see which modules already have a full shiny Jenkins working and disable the other CIs as we go.

In fact, I believe we only need Circle for Coveralls, correct?

**Pull request closed without merging**
